# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
# url: "https://justanton.github.io"
url: "http://127.0.0.1:4000/"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: ""

# Let people connect & engage with you through social media.
social:
  twitter_handle: ""

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Local Hack Day Ruhr | 3 Dezember 2016"
  description: "Local Hack Day Ruhr brings together the students on December 3rd 2016 for 12 hours of learning, building and sharing."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Local Hack Day Ruhr"
  description: ""
  date:        "3 Dezember 2016"
  location:    "Duisburg, Germany"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "blue" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          url: "https://localhackday.mlh.io/register/?id=essen&city_name=Duisburg%2C%20Germany"
          redirect_uri: "https://justanton.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:lhdruhr@gmail.com"

  about:
    description: >
      On December 3rd, meet new people from your local community of tech-enthusiasts, learn new skills and celebrate technology during 12 unforgettable hours with free food and swag.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          Meet new like-minded people, learn from each other and work in teams.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          Create something you care about in under 12 hours.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          Share your knowledge with others and build a better, stronger community.

  # Frequently asked questions.
  faq:
    - question: "What is a Local Hack Day Ruhr?"
      answer: >
        Local Hack Day Ruhr is a 12-hours event with the goal to bring together tech-enthusiasts from the Ruhr area
        and make that community more connected.
        Hack Day is very close in spirit to Hackathons, and it is designed to make it easier for newcomers to
        get acquainted with the format of a [Hackathon](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).


        The program includes cool workshops and talks, to boost your tech skills, and the main part is work in teams on projects of your interest.
    - question: "How much does it cost?"
      answer: >
        **Nothing.** Attending a Local Hack Day is free.
        We will have some food and also **free** surprise gifts ;D.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a University/Fachhochschule are eligible to attend.
        Please, bring your valid student ID with you to the event.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at the [Franz-Haniel-Platz, 47119 Duisburg (Social Impact Lab).](https://www.google.de/maps/place/Social+Impact+Lab+Duisburg/@51.451535,6.7330771,15z/data=!4m5!3m4!1s0x0:0xc406eb74bbad6e1f!8m2!3d51.451535!4d6.7330771)
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).
    - question: "Any other questions?"
      answer: >
        Feel free to write us to [lhdruhr@gmail.com](mailto:lhdruhr@gmail.com)

  timeline:
    days:
      - day: "Saturday, Dec 3th"
        events:
          - title: "Registration"
            time: "8:30 - 9:00"
            place: ""
          - title: "Welome Keynote"
            time: "9:00"
            place: ""
          - title: "Workshops/Talks"
            time: "9:45 - 12:00"
          - title: "Lunch"
            time: "12:00 - 13:00"
            place: ""
          - title: "Dinner"
            time: "18:00 - 19:00"
            place: ""
          - title: "Projects Demos, optional"
            time: "20:00 - 21:00"
            place: ""
          - title: "End"
            time: "21:00"
            place: ""

  sponsor:
    # sponsorus: >
    # sections:
    #   - image: "
    #     url: ""
    #     description: >
    sectionSupport:
      - image: "images/sil_logo.png"
        url: "http://duisburg.socialimpactlab.eu/"
        description: >
      - image: "images/mlh-logo.png"
        url: "https://mlh.io/"
        description: >

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
