# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
# url: "https://justanton.github.io"
url: "http://127.0.0.1:4000/"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: ""

# Let people connect & engage with you through social media.
social:
  twitter_handle: ""

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Local Hack Day Ruhr | 3 Dezember 2016"
  description: ""
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Local Hack Day Ruhr"
  description: ""
  date:        "3 Dezember 2016"
  location:    "Duisburg, Germany"

  trust_badge:
    year:   "2017"  # season year
    region: "eu"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          url: "https://localhackday.mlh.io/register/?id=essen&city_name=Duisburg%2C%20Germany"
          redirect_uri: "https://justanton.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor"
        href: "mailto:lhdruhr@gmail.com"

  about:
    description: >
      Need to change this later.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          Meet new like-minded people, collaborate, and learn from each other.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          Create something you are passionate about in under 12 hours.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          Share your knowledge with others and build a better, stronger community.

  # Frequently asked questions.
  faq:
    - question: "What is a Local Hack Day Ruhr?"
      answer: >
        Local Hack Day Ruhr is an invention marathon. Students come together to build cool
        software & hardware hacks in about 12 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        **Nothing.** Attending a Local Hack Day is free.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a University/Fachhochschule or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at the *Franz-Haniel-Platz, 47119 Duisburg (Social Impact Lab).*
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
